Add section for keyboard navigation and pane navigator #107
IgniteUI/igniteui-xplat-docs pull request #108
Opened 2021-04-06 10:46 UTC by zhosti

2021-04-06 13:16 UTC, igdmdimitrov commented on doc/en/components/dock-manager.md
> + - <kbd>Cmd/Ctrl + F8</kbd> Shows the navigator and iterate panes and documents starting from the first document forward
```suggestion
 - <kbd>Cmd/Ctrl + F7</kbd> / <kbd>Cmd/Ctrl + F8</kbd> Shows the navigator and iterate panes and documents starting from the first document forward
```

Where possible, combine shortcuts that have the same function.

2021-04-06 13:21 UTC, igdmdimitrov commented on doc/en/components/dock-manager.md
> +### Docking Combinations
Split sections to be as following - Docking, Navigating and Other (for close). Also add 'ALT + F6' and 'ALT + SHIFT + F6' combinations.

2021-04-06 13:23 UTC, igdmdimitrov commented on doc/en/components/dock-manager.md
> +Practice all of the above mentioned actions in the demo sample [`demo`](#web-components-dock-manager-overview-example).
```suggestion
Practice all of the above mentioned actions in the sample [`demo`](#web-components-dock-manager-overview-example). 
```

2021-04-06 13:29 UTC, igdmdimitrov commented on doc/en/components/dock-manager.md
> + - <kbd>Alt + F3</kbd> Closes tab/document
```suggestion
 - <kbd>Alt + F3</kbd> Closes the active pane
```

2021-04-06 13:40 UTC, igdmdimitrov commented on doc/en/components/dock-manager.md
> +Here is a full set of the key combinations:
```suggestion
Keyboard navigation enhances the accessibility of the **Dock Manager** and provides a rich variety of interactions to the end-user - navigate through all panes, split the view in multiple directions through docking the active pane, etc. The shortcuts are as follows:
```

2021-04-07 10:53 UTC, zhosti commented
closes #107

2021-04-07 14:02 UTC, igdmdimitrov commented on doc/en/components/dock-manager.md
> +With the [`allowFloatingPanesResize`]({environment:infragisticsBaseUrl}/products/ignite-ui/dock-manager/docs/typescript/latest/interfaces/igcdockmanagercomponent.html#allowfloatingpanesresize) proper
```suggestion
With the [`allowFloatingPanesResize`]({environment:infragisticsBaseUrl}/products/ignite-ui/dock-manager/docs/typescript/latest/interfaces/igcdockmanagercomponent.html#allowfloatingpanesresize) property you can choose whether to allow floating panes to be resized, by default the property value is `true`. If the value is set to `false`, none of the floating panes can be resized.
```

2021-04-07 14:06 UTC, igdmdimitrov commented on doc/en/components/dock-manager.md
> +The [`floatingLocation`]({environment:infragisticsBaseUrl}/products/ignite-ui/dock-manager/docs/typescript/latest/interfaces/igcsplitpane.html#floatinglocation), [`floatingWidth`]({environment:infrag
```suggestion
The [`floatingLocation`]({environment:infragisticsBaseUrl}/products/ignite-ui/dock-manager/docs/typescript/latest/interfaces/igcsplitpane.html#floatinglocation), [`floatingWidth`]({environment:infragisticsBaseUrl}/products/ignite-ui/dock-manager/docs/typescript/latest/interfaces/igcsplitpane.html#floatingwidth) and [`floatingHeight`]({environment:infragisticsBaseUrl}/products/ignite-ui/dock-manager/docs/typescript/latest/interfaces/igcsplitpane.html#floatingheight) properties represent absolute dimensions in pixels. With the [`floatingResizable`]({environment:infragisticsBaseUrl}/products/ignite-ui/dock-manager/docs/typescript/latest/interfaces/igcsplitpane.html#floatingresizable) property you can set whether floating pane resizing is allowed, the default value of the property is `false`. Please note that these properties are applied only for the split panes in the [`floatingPanes`]({environment:infragisticsBaseUrl}/products/ignite-ui/dock-manager/docs/typescript/latest/interfaces/igcdockmanagerlayout.html#floatingpanes) array.
```

2021-04-07 14:33 UTC, gedinakova commented
@zhosti "...like navigating through all panes, **spliting** the view in multiple directions through docking the active pane, etc." - should be **splitting**.

2021-04-07 14:36 UTC, gedinakova commented
In "Navigating" section, we should probably change 'Focus" to 'Focuses" similar to the other two sections.

2021-04-07 14:41 UTC, gedinakova commented
@zhosti "With the allowFloatingPanesResize property you can choose whether to allow floating panels to be resized..." => "whether resizing floating panes is allowed..."

2021-04-07 14:59 UTC, gedinakova commented
@zhosti "With the floatingResizable property you can determine whether floating pane resizing is allowed" => "The `floatingResizable`(link) property, which by default is set to true, determines whether a specific floating pane can be resized. This value will overwrite the value of the global `allowFloatingPanesResize` property.

2021-04-07 15:28 UTC, gedinakova commented
> @zhosti "With the floatingResizable property you can determine whether floating pane resizing is allowed" => "The `floatingResizable`(link) property, which by default is set to true, determines whether a specific floating pane can be resized. This value will overwrite the value of the global `allowFloatingPanesResize` property.

This comment was about the section in Floating panes, describing the `floatingResizable` property, not the `allowFloatingPanesResize` in Usage.

2021-04-07 19:54 UTC, HUSSAR-mtrela approved these changes

2021-04-07 19:55 UTC, HUSSAR-mtrela requested changes
please target vnext branch instead of master branch

2021-04-09 07:59 UTC, igdmdimitrov approved these changes

2021-04-09 09:10 UTC, gedinakova commented
@zhosti The demo link does not work (under keyboard navigation). It should be "#web-components-dock-manager-example" instead of "#web-components-dock-manager-overview-example".

2021-04-09 20:23 UTC, HUSSAR-mtrela approved these changes

2021-04-09 20:24 UTC, merged