Add a topic that shows usage of react coponents within Next.js
IgniteUI/igniteui-xplat-docs pull request #1147
Opened 2024-01-18 14:13 UTC by mddragnev

2024-01-23 12:23 UTC, ChronosSF requested changes

2024-01-23 12:23 UTC, ChronosSF commented on doc/en/components/nextjs-usage.md
> +> Implementing lazy loading for components can enhance performance, but it is advisable to use it exclusively when the components are not immediately visible on the page.
You should add a see also paragraph at the end with a few generic links to our docs and a link to nextjs docs too

2024-01-23 13:32 UTC, aatanasov2 commented
@ChronosSF  I've slightly edited the meta description and the keywords 

title: Use {ProductName} components in Next.js application | Infragistics
_description: Use Infragistics' {Platform} components to create apps and improve data visualization with the world’s fastest {Platform} data grid and charts in Next.js. 
_keywords: {ProductName} Next.js, {ProductName} Components in Next.js, Infragistics

2024-01-23 14:49 UTC, aatanasov2 approved these changes

2024-01-26 12:09 UTC, ChronosSF approved these changes

2024-01-26 12:09 UTC, merged