Mdd 21.1 date picker
IgniteUI/igniteui-xplat-docs pull request #115
Opened 2021-04-14 15:43 UTC by mddifilippo89

2021-04-14 16:05 UTC, mddifilippo89 commented
@HUSSAR-mtrela  

I got latest on vnext and my branch is up to date, with no merge conflicts

2021-04-14 16:10 UTC, HUSSAR-mtrela requested changes
change the first paragraph to:
The $ProductName$ DatePicker allows ...

2021-04-14 16:10 UTC, HUSSAR-mtrela commented on doc/en/components/charts/features/chart-tooltips.md
> +## Custom Tooltips in Data Chart
get latest and resolve conflict

2021-04-14 16:10 UTC, HUSSAR-mtrela commented on doc/en/components/editors/date-picker.md
> +
missing a sample showing styling features

2021-05-25 15:40 UTC, HUSSAR-mtrela commented
@mddifilippo89 resolve conflicts

2021-05-25 15:49 UTC, merged