[React] Adding all combo topics for React
IgniteUI/igniteui-xplat-docs pull request #1151
Opened 2024-01-22 14:56 UTC by georgianastasov

Closes: #1054

2024-01-22 14:58 UTC, georgianastasov commented
Waiting for a templates sample to be added in this PR [here](https://github.com/IgniteUI/igniteui-react-examples/pull/442) to complete the templates topic.

2024-04-22 09:12 UTC, IMinchev64 requested changes

2024-04-22 09:12 UTC, IMinchev64 commented on doc/en/components/inputs/combo/templates.md
Not part of the changeset so cannot reference the specific lines but the snippets for the item template and the group header template appear to be for web components.

2024-04-22 14:59 UTC, IMinchev64 requested changes

2024-04-22 14:59 UTC, IMinchev64 commented on doc/en/components/inputs/combo/templates.md
> +<!-- WebComponents -->
Please also add the item template and the group header template snippets for React as currently they seem to be missing

2024-04-23 07:29 UTC, IMinchev64 approved these changes

2024-04-23 08:34 UTC, merged