Add Dock Manager desktop integration topic
IgniteUI/igniteui-xplat-docs pull request #127
Opened 2021-05-18 14:43 UTC by DiyanDimitrov

Closes IgniteUI/dock-manager#136

2021-05-18 21:03 UTC, gedinakova requested changes

2021-05-18 21:03 UTC, gedinakova commented on doc/en/components/dock-manager-electron.md
> +We are using the native [`window.open()`](https://developer.mozilla.org/en-US/docs/Web/API/Window/open) method to open a new window in the Renderer process. We set the `nativeWindowOpen` option to `t
This paragraph is a little disconnected from the previous one but I don't have a better suggestion.

2021-05-18 21:05 UTC, gedinakova commented
The in-page navigation tree looks strange:
![image](https://user-images.githubusercontent.com/16817847/118723242-d5856a00-b835-11eb-80f9-57155370d98d.png)

2021-05-20 11:31 UTC, gedinakova approved these changes

2021-05-25 15:07 UTC, HUSSAR-mtrela approved these changes

2021-05-25 15:49 UTC, merged