mdd-added-what's-new
IgniteUI/igniteui-xplat-docs pull request #128
Opened 2021-05-21 22:02 UTC by mddifilippo89

mdd-added-what's-new

2021-05-21 22:02 UTC, mddifilippo89 commented
Waiting on final production versions to update {PackageVerChangedCharts}

2021-05-24 19:06 UTC, HUSSAR-mtrela requested changes

2021-05-24 19:06 UTC, HUSSAR-mtrela commented on docfx/en/components/toc.json
> +    "href": "whats-new-dv.md",
add "general-" prefix

2021-05-24 19:06 UTC, HUSSAR-mtrela commented on doc/en/components/whats-new-dv.md
> +---
add "general-" prefix to file name

2021-05-24 19:06 UTC, HUSSAR-mtrela commented on docfx/jp/components/toc.json
> +    "href": "whats-new-dv.md",
add "general-" prefix

2021-05-24 19:06 UTC, HUSSAR-mtrela commented on docfx/kr/components/toc.json
> +    "href": "whats-new-dv.md",
add "general-" prefix

2021-05-24 20:13 UTC, HUSSAR-mtrela approved these changes

2021-05-24 20:13 UTC, merged