feat(dock-manager): add styling topic
IgniteUI/igniteui-xplat-docs pull request #159
Opened 2021-09-08 11:22 UTC by zhosti

Closes #158

2021-09-08 11:33 UTC, gedinakova requested changes

2021-09-08 11:33 UTC, gedinakova commented on doc/en/components/dock-manager.md
> +The Dock Manager use a sahadow DOM to encapsulate his styles and behaviors. As a result, you can't simply target their internals with the usual CSS selectors. That is why we expose components `parts`
The Dock Manager use**s** a shadow ....

2021-09-08 11:33 UTC, gedinakova commented on doc/en/components/dock-manager.md
> +The Dock Manager use a sahadow DOM to encapsulate his styles and behaviors. As a result, you can't simply target their internals with the usual CSS selectors. That is why we expose components `parts`
As a result, you can't simply target its internal elements with ....

2021-09-08 11:33 UTC, gedinakova commented on doc/en/components/dock-manager.md
> +In the following example, we will demonstrate the ability of customizing the Dock Manager through some of the exposed parts that we've provided.
In the following example, we demonstrate the ability of customizing the Dock Manager through some of the CSS parts that we've exposed.

2021-09-08 11:33 UTC, gedinakova commented on doc/en/components/dock-manager.md
>  ## Themes
Maybe we could make Themes a sub category of styling

2021-09-08 13:25 UTC, gedinakova requested changes

2021-09-08 13:25 UTC, gedinakova commented on doc/en/components/dock-manager.md
> +The Dock Manager uses a sahadow DOM to encapsulate his styles and behaviors. As a result, you can't simply target its internal elements with the usual CSS selectors. That is why we expose components
'sahadow' => 'shadow'

2021-09-08 13:59 UTC, gedinakova approved these changes

2021-09-09 18:10 UTC, HUSSAR-mtrela requested changes

2021-09-09 18:10 UTC, HUSSAR-mtrela commented on doc/en/components/dock-manager.md
> +           github-src="layouts/dock-manager/styling">
this sample is missing in Blazor repo, React repo, and Angular repo

https://github.com/IgniteUI/igniteui-blazor-examples/tree/vnext/samples/layouts/dock-manager

https://github.com/IgniteUI/igniteui-react-examples/tree/vnext/samples/layouts/dock-manager

https://github.com/IgniteUI/igniteui-angular-samples/tree/vNext/src/app/layouts/dock-manager/dock-manager-sample

2021-09-15 15:45 UTC, HUSSAR-mtrela commented
do not merge this PR - see comments in my review

2021-09-17 09:13 UTC, gedinakova commented on doc/en/components/dock-manager.md
> +```razor
I believe marking with ```razor is enough. However, are you sure about the code itself?

2021-09-17 09:21 UTC, gedinakova approved these changes

2021-09-21 08:56 UTC, gedinakova commented
@HUSSAR-mtrela Martin, could you, please, check if this PR is ready to be merged now?

2021-09-27 06:23 UTC, gedinakova commented
@HUSSAR-mtrela Hi Martin, we really need this PR merged. We've already released the package last week, so we have to demonstrate the CSS parts we've added and how they can use it to style the component. This was a feature requested by a few customers, so they are expecting it. Can you, please, check if everything is OK now?

2021-09-27 17:58 UTC, HUSSAR-mtrela approved these changes

2021-09-27 17:58 UTC, merged