docs(navbar): add topic - vNext
IgniteUI/igniteui-xplat-docs pull request #202
Opened 2021-10-28 10:14 UTC by igdmdimitrov

Closes #175

2021-11-01 14:09 UTC, DiyanDimitrov commented on doc/en/components/navbar.md
> +  <span slot="end" class="material-icons">more_vert</span>
I would suggest to use our icon component instead of the material icons font.

2021-11-03 08:03 UTC, DiyanDimitrov approved these changes

2021-11-03 13:59 UTC, gedinakova requested changes
Add API Links

2021-11-04 10:13 UTC, gedinakova approved these changes

2021-11-05 14:15 UTC, HUSSAR-mtrela approved these changes

2021-11-05 14:15 UTC, merged