Check in DatePicker topic
IgniteUI/igniteui-xplat-docs pull request #28
Opened 2020-12-07 22:48 UTC by agoldenbaum

2020-12-07 23:56 UTC, pamelabrasil commented on doc/en/components/date-picker.md
> +
add bullets here to describe each area 
Text Area- the text area will display the selected date, stored in the value property of the editor
Calendar -
Clear button -

2020-12-07 23:58 UTC, pamelabrasil commented on doc/en/components/date-picker.md
> +
explain the code snippet with a description and add some more things to - for example setting specific properties with comments

2020-12-08 01:53 UTC, HUSSAR-mtrela requested changes

2020-12-08 01:53 UTC, HUSSAR-mtrela commented on doc/en/components/date-picker.md
> +mentionedTypes: []
in the `mentionedTypes` array, add name of class(es) that have implementation of properties mentioned in this topic

2020-12-08 01:53 UTC, HUSSAR-mtrela commented on doc/en/components/date-picker.md
> +);
change it to single line

2020-12-09 20:06 UTC, HUSSAR-mtrela approved these changes

2020-12-09 20:06 UTC, merged