Add mask input topic
IgniteUI/igniteui-xplat-docs pull request #401
Opened 2022-06-16 10:14 UTC by onlyexeption

Closes #352

2022-06-27 12:47 UTC, igdmdimitrov commented on doc/en/components/inputs/mask-input.md
> +    <span slot="helper-text">This is some helper text</span>
Change helper text to something related to the sample, for example "Phone number" or something else.

2022-06-27 12:59 UTC, igdmdimitrov commented on doc/en/components/inputs/mask-input.md
> +    <igc-icon name="github" slot="suffix"></igc-icon>
Change the prefix icon to some kind of phone. You can delete the suffix.

2022-06-28 11:18 UTC, rkaraivanov commented on doc/en/components/inputs/mask-input.md
> +
| Mask Character | Description |
| :--- | :--- |
| \ | Escapes a mask flag and turns it into a literal. |

2022-06-28 11:20 UTC, rkaraivanov commented on doc/en/components/inputs/mask-input.md
> +
Also, there should be a mention about required flags and validation.
Refer to [this](https://github.com/IgniteUI/igniteui-webcomponents/wiki/Masked-input#functionality) section

2022-06-28 11:22 UTC, rkaraivanov requested changes
Except the comments above, LGTM

2022-06-29 07:01 UTC, igdmdimitrov commented on doc/en/components/inputs/mask-input.md
> +These flags also participate in the component validation - i.e., the input becomes invalid if some, but not all required positions are filled (no positions filled/empty value is still a responsibilit
```suggestion
These flags also participate in the component validation - i.e., the input becomes invalid if some but not all required positions are filled (no positions filled/empty value is still a responsibility of `required`). This applies to both stand-alone inputs and when included in a form.
```

2022-06-29 07:08 UTC, igdmdimitrov approved these changes

2022-06-29 07:28 UTC, rkaraivanov requested changes

2022-06-29 07:28 UTC, rkaraivanov commented on doc/en/components/inputs/mask-input.md
> +| C | any keyboard character |
I suggest using the table from the specification. Currently there is no distinction about which mask flags are required and which are optional.

2022-07-22 21:51 UTC, HUSSAR-mtrela approved these changes

2022-07-22 21:54 UTC, HUSSAR-mtrela approved these changes

2022-07-22 21:55 UTC, merged