remove child dependencies from defineComponents
IgniteUI/igniteui-xplat-docs pull request #424
Opened 2022-07-29 09:15 UTC by onlyexeption

Closes #419

2022-08-04 07:30 UTC, mtsvyatkova approved these changes

2022-08-08 19:28 UTC, HUSSAR-mtrela approved these changes

2022-08-08 19:29 UTC, HUSSAR-mtrela requested changes
please resolve merge conflict with vnext branch

2022-08-10 12:59 UTC, HUSSAR-mtrela approved these changes

2022-08-10 12:59 UTC, merged