updated few topics
IgniteUI/igniteui-xplat-docs pull request #556
Opened 2022-11-01 12:50 UTC by tishko0

Recreated PR and updated topics as per your request here: https://github.com/IgniteUI/igniteui-xplat-docs/pull/528

2022-11-01 14:02 UTC, HUSSAR-mtrela requested changes

2022-11-02 10:16 UTC, tishko0 commented on doc/en/components/grids/_shared/live-data.md
> -<!-- end: Angular -->
re-added

2022-11-02 10:16 UTC, tishko0 commented on doc/en/components/grids/_shared/live-data.md
> -<!-- Angular -->
re-added

2022-11-02 10:16 UTC, tishko0 commented on doc/en/components/grids/_shared/live-data.md
> +<{ComponentInstance} [data]="data"></{ComponentInstance}>
replaced

2022-11-02 10:16 UTC, tishko0 commented on doc/en/components/grids/_shared/live-data.md
>  ```
replaced

2022-11-02 10:16 UTC, tishko0 commented on doc/en/components/grids/_shared/live-data.md
> -
done

2022-11-02 16:48 UTC, HUSSAR-mtrela approved these changes

2022-11-02 16:48 UTC, merged