chore(*): package updates and node 16 update
IgniteUI/igniteui-xplat-docs pull request #561
Opened 2022-11-02 12:17 UTC by kdinev

Trying to restore the workflow

2022-11-09 20:48 UTC, HUSSAR-mtrela requested changes

2022-11-09 20:48 UTC, HUSSAR-mtrela commented on .github/workflows/nodejs.yml
> +    - name: npm install
can we use "yarn install" instead of "npm install" command? if so then we would not need package-lock.json file in your PR

2022-12-05 21:54 UTC, HUSSAR-mtrela reviewed
let's hold on with this PR until we are done with WC release 12/9/22

2022-12-05 22:47 UTC, gmurray81 commented
No, I think we need it. Webpack is doing pretty bad things with the current setup, such as loading the full cjs modules in a lot of instances.

2022-12-05 23:13 UTC, gmurray81 commented
Oh no, I was actually talking about a different PR that I just sent you @HUSSAR-mtrela

2022-12-05 23:13 UTC, gmurray81 commented
Not this one.

2022-12-08 16:57 UTC, gmurray81 approved these changes

2023-02-02 12:03 UTC, ChronosSF approved these changes

2023-02-02 12:05 UTC, merged