docs(pivot): port overview topic
IgniteUI/igniteui-xplat-docs pull request #608
Opened 2022-11-28 15:42 UTC by dkamburov

2022-11-28 18:40 UTC, HUSSAR-mtrela requested changes

2022-11-28 18:40 UTC, HUSSAR-mtrela commented on doc/en/components/grids/pivot-grid/overview.md
> +The `PivotGridComponent` gives the ability to users to configure and display their data in a multi-dimensional pivot table structure.
replace all "PivotGridComponent" with "{PivotGridName}"

2022-12-05 16:34 UTC, skrustev commented on doc/en/components/grids/pivot-grid/overview.md
> +As part of the pivot grid some additional predefined dimensions are exposed for easier configuration:
There are multiple places where `Pivot Grid` is written in small case `pivot grid`

2022-12-05 16:34 UTC, skrustev commented on doc/en/components/grids/pivot-grid/overview.md
> +`IPivotConfiguration` is the interface that describes the current state of the `PivotGrid` component. With it the developer can declare fields of the data as **rows**, **columns**, **filters** or **v
For Blazor i think the names of the interfaces should be replaced with the `IgbPivotConfiguration`, `IgbPivotDimension` and `IgbPivotValue` classes

2022-12-05 16:34 UTC, skrustev commented on doc/en/components/grids/pivot-grid/overview.md
> +| Merging the dimension members is case sensitive| The pivot grid creates groups and merges the same (case sensitive) values. But the dimensions provide `MemberFunction` and this can be changed there
For Angular only regarding `MemberFunction` as well (if the table can work that way anyway)

2022-12-06 22:15 UTC, HUSSAR-mtrela approved these changes

2022-12-06 22:15 UTC, merged