feat(combo): provide component documentation
IgniteUI/igniteui-xplat-docs pull request #616
Opened 2022-11-30 15:49 UTC by SisIvanova

2022-11-30 19:36 UTC, HUSSAR-mtrela requested changes
use PascalCase in API links mentioned in **ALL** paragraphs, e.g. 
GroupKey instead of `group-key` 
FilterKey instead of `filterKey`

2022-11-30 19:36 UTC, HUSSAR-mtrela commented on doc/en/components/grids/combo/overview.md
> +`list-wrapper` | A wrapper that holds the filter-input and the `igc-combo-list` component.
replace `igc-combo-list` with `ComboList`

2022-11-30 19:36 UTC, HUSSAR-mtrela commented on doc/en/components/grids/combo/overview.md
> +The reversed action is also available using the combo `deselect()` method. In this case, if an empty array is passed, all of the options in the combobox list will be deselected.
remove "()"

2022-11-30 19:36 UTC, HUSSAR-mtrela commented on doc/en/components/grids/combo/features.md
> +mentionedTypes: ['Combo']
add 'ComboItem' and 'ComboList' to mentionedTypes

2022-12-07 11:46 UTC, simeonoff approved these changes

2022-12-08 15:15 UTC, SisIvanova commented on doc/en/components/grids/combo/overview.md
> +{Platform} ComboBox is a lightweight editor that enables users to easily select, filter, and group different predefined options in a provided list. The component also supports options for {Platform}
@radomirchev The custom values feature is not yet implemented.

2022-12-14 13:00 UTC, ChronosSF commented
@SisIvanova , these topics shouldn't be under grids, should they?

2022-12-14 13:16 UTC, ChronosSF commented
@HUSSAR-mtrela , I wanted to test whether or not the API refs generate links properly following your previous review but they all seem to not generate any links. Then I remembered there was some fundamental issue with the api links for WC. Am I remembering correctly and can we merge it now?

TBH without the links the props will make no sense in pascal case so I am a bit worried about the docs.

2022-12-14 13:24 UTC, ChronosSF commented
Interestingly digging into this further I noticed that from the following paragraph:

The {ProductName} Combo component supports most of the `Input` properties, such as `Required`, `Disabled`, `Autofocus`, `Invalid`, etc. The component also exposes two methods bound to its validation:

the first two properties don't generate links, the latter two do, but all 4 seem to be present in the api page the ones that do point to.

So there seems to be some issue in the generator...

2022-12-14 18:16 UTC, HUSSAR-mtrela approved these changes

2022-12-14 18:16 UTC, merged