Update combo docs to include Blazor
IgniteUI/igniteui-xplat-docs pull request #733
Opened 2023-03-28 08:23 UTC by simeonoff

This PR must be tested against https://github.com/IgniteUI/igniteui-blazor-examples/pull/321

2023-03-30 14:28 UTC, ChronosSF commented
LGTM

2023-03-30 14:28 UTC, ChronosSF approved these changes

2023-03-30 14:41 UTC, HUSSAR-mtrela requested changes

2023-03-30 14:41 UTC, HUSSAR-mtrela commented on doc/en/components/inputs/combo/overview.md
> +    private object[] UKCities;
change to "Cities"

2023-03-30 14:41 UTC, HUSSAR-mtrela commented on doc/en/components/inputs/combo/overview.md
> +        this.UKCities = new object[] { "UK01", "UK02", "UK03", "UK04", "UK05" };
change to "Cities"

2023-03-30 14:41 UTC, HUSSAR-mtrela commented on doc/en/components/inputs/combo/overview.md
> +        this.Combo.Select(UKCities);
change to "Cities"

2023-03-30 14:41 UTC, HUSSAR-mtrela commented on doc/en/components/inputs/combo/overview.md
> +        this.Combo.Deselect(UKCities);
change to "Cities"

2023-03-31 16:45 UTC, HUSSAR-mtrela approved these changes

2023-04-03 14:20 UTC, merged