refactor(select): add razor snippets
IgniteUI/igniteui-xplat-docs pull request #739
Opened 2023-03-29 07:13 UTC by simeonoff

Closes #712

2023-03-30 12:43 UTC, ChronosSF approved these changes

2023-03-30 13:59 UTC, HUSSAR-mtrela requested changes

2023-03-30 13:59 UTC, HUSSAR-mtrela commented on doc/en/components/inputs/select.md
> +    ...
remove "..."

2023-03-30 13:59 UTC, HUSSAR-mtrela commented on doc/en/components/inputs/select.md
> +    ...
remove "..."

2023-03-31 13:27 UTC, HUSSAR-mtrela approved these changes

2023-03-31 13:45 UTC, merged