Change a snippet in the Display Density topic
IgniteUI/igniteui-xplat-docs pull request #793
Opened 2023-04-20 13:58 UTC by mddragnev

2023-04-24 14:06 UTC, mddragnev commented
@HUSSAR-mtrela Why are u setting in-development label?

2023-06-15 13:51 UTC, dkamburov commented on doc/en/components/grids/_shared/display-density.md
>   <!-- WebComponents -->
The code snippet bellow is wrong. `display-density="Cosy"` is wrong, should be display-density="cosy"

2023-06-15 13:52 UTC, dkamburov commented on doc/en/components/grids/_shared/display-density.md
>   <!-- WebComponents -->
And there is one more occurrence of it in this doc

2023-06-15 14:10 UTC, dkamburov requested changes
We need to remove property editor panel from code snippets and ComponentRenderer related code

2023-06-27 13:00 UTC, dkamburov approved these changes

2023-06-27 13:00 UTC, merged