Grid Filtering - Fix WC/Blazor grid snippets and sections. Add styling.
IgniteUI/igniteui-xplat-docs pull request #809
Opened 2023-05-03 12:11 UTC by MayaKirova

2023-05-04 13:40 UTC, HUSSAR-mtrela requested changes

2023-05-04 13:40 UTC, HUSSAR-mtrela commented on doc/en/components/grids/_shared/filtering.md
> +<!-- end:Angular -->
missing space after "end:"

2023-05-04 13:40 UTC, HUSSAR-mtrela commented on doc/en/components/grids/_shared/filtering.md
> +<!-- end:Angular -->
missing space after "end:"

2023-05-04 13:40 UTC, HUSSAR-mtrela commented on doc/en/components/grids/_shared/filtering.md
> +<!-- end:Angular, WebComponents -->
missing space after "end:"

2023-05-17 14:34 UTC, mddragnev commented
The first sample that is used in the docs is filtering-options and it shows excel style filtering instead of quick filtering. Probably not a big deal but I think in the filtering topic should be quick filtering

2023-06-16 08:48 UTC, MayaKirova commented
@mddragnev Sample mode updated here: https://github.com/IgniteUI/igniteui-xplat-examples/pull/199
Also updated topic to match.

2023-06-19 14:37 UTC, mddragnev approved these changes

2023-06-27 13:14 UTC, dkamburov commented
@HUSSAR-mtrela can you please do a review again

2023-06-27 13:14 UTC, dkamburov approved these changes

2023-06-27 22:59 UTC, HUSSAR-mtrela commented on doc/en/components/grids/_shared/filtering.md
> +<!-- Angular, WebComponents -->
there is no end tag for this build flag

2023-06-27 23:01 UTC, HUSSAR-mtrela requested changes
see my comment

2023-06-29 12:45 UTC, MayaKirova commented on doc/en/components/grids/_shared/filtering.md
> +<!-- Angular, WebComponents -->
Thanks, second one has been removed.

2023-07-06 17:06 UTC, HUSSAR-mtrela approved these changes

2023-07-06 17:14 UTC, merged