Update tree grid overview topic.
IgniteUI/igniteui-xplat-docs pull request #853
Opened 2023-06-13 13:10 UTC by MayaKirova

2023-06-21 16:38 UTC, mddragnev commented
The first sample for WC has wrong fields for ID salary and productivity columns resulting in no data.

2023-06-21 17:17 UTC, mddragnev requested changes

2023-06-29 10:16 UTC, MayaKirova commented on doc/en/components/grids/tree-grid/overview.md
Overview sample updated here: https://github.com/IgniteUI/igniteui-xplat-examples/pull/253

2023-10-23 12:41 UTC, IMinchev64 approved these changes

2023-10-24 12:44 UTC, mddragnev commented on doc/en/components/grids/tree-grid/overview.md
> +    --igx-grid-header-background: #494949;
These should be --ig-grid..

2023-12-05 16:06 UTC, mddragnev approved these changes

2023-12-05 22:03 UTC, merged