Update event handlings in code snippets to work.
IgniteUI/igniteui-xplat-docs pull request #858
Opened 2023-06-15 06:17 UTC by skrustev

2023-06-15 10:09 UTC, MayaKirova submitted a review, later dismissed

2023-06-20 16:36 UTC, HUSSAR-mtrela commented
@MayaKirova can you please resolve above conflict in groupby.md file?
![image](https://github.com/IgniteUI/igniteui-xplat-docs/assets/11665978/4315d8fa-0005-4561-82cd-6a60e7b73f57)

2023-06-20 16:37 UTC, HUSSAR-mtrela requested changes
@MayaKirova can you please resolve above conflict in groupby.md file?
![image](https://github.com/IgniteUI/igniteui-xplat-docs/assets/11665978/4315d8fa-0005-4561-82cd-6a60e7b73f57)

2023-07-06 15:54 UTC, HUSSAR-mtrela approved these changes

2023-07-06 15:55 UTC, merged