Address PR comments for cell editing topic
IgniteUI/igniteui-xplat-docs pull request #912
Opened 2023-07-05 13:30 UTC by onlyexeption

Address PR comments from here -https://github.com/IgniteUI/igniteui-xplat-docs/pull/861

2023-07-05 14:17 UTC, MayaKirova requested changes

2023-07-05 14:17 UTC, MayaKirova commented on doc/en/components/grids/_shared/cell-editing.md
> +    this._bind = () => {
`this._bind` is not necessary, can be removed from the snippets.

2023-07-05 14:17 UTC, MayaKirova commented on doc/en/components/grids/_shared/cell-editing.md
> +public webTreeGridCellEdit(event: CustomEvent): void {
Could also have the type `CustomEvent<IgcGridEditEventArgs>`

2023-07-12 10:52 UTC, onlyexeption commented on doc/en/components/grids/_shared/cell-editing.md
> +Working sample of the above can be found here for further reference:
Added PR [#264](https://github.com/IgniteUI/igniteui-xplat-examples/pull/264)

2023-12-21 10:19 UTC, MayaKirova approved these changes

2023-12-21 13:47 UTC, merged