Add Dock Manager customization topic
IgniteUI/igniteui-xplat-docs pull request #932
Opened 2023-07-24 11:37 UTC by onlyexeption

2023-07-25 13:41 UTC, mtsvyatkova requested changes

2023-07-25 13:41 UTC, mtsvyatkova commented on doc/en/components/layouts/dock-manager-customization.md
> +mentionedTypes: ['DockManager']
Add 'ContentPane' as mentioned type

2023-07-25 13:41 UTC, mtsvyatkova commented on doc/en/components/layouts/dock-manager-customization.md
> +### Customizing {Platform} Dock Manager
This section's title needs to be the same size as the others in the topic: '## Customizing {Platform} Dock Manager'

2023-07-25 13:41 UTC, mtsvyatkova commented on doc/en/components/layouts/dock-manager-customization.md
> +### Demo
We could skip the 'Demo' subtitles as they are repeating in the left-side navigation menu. In the other dock manager topics we are displaying samples without any subtitle.

2023-07-25 13:41 UTC, mtsvyatkova commented on doc/en/components/layouts/dock-manager-customization.md
> +    contentId: 'content3',
```suggestion
    contentId: 'content3',
```

2023-09-07 15:15 UTC, ChronosSF submitted a review, later dismissed

2023-09-11 12:07 UTC, mtsvyatkova approved these changes

2023-09-11 12:16 UTC, igdmdimitrov commented on doc/en/components/layouts/dock-manager-customization.md
> +With the `showPaneHeaders` property of the DockManager, developers now have the flexibility to control the visibility of pane headers within the `layout`. By default, `showPaneHeaders` is set to **tr
Update this section - `showPaneHeaders` was later modified to be either `'onHoverOnly'` or `'always'`

2023-09-25 15:36 UTC, merged