Enable display density react topic
IgniteUI/igniteui-xplat-docs pull request #958
Opened 2023-08-31 11:39 UTC by mddragnev

2023-09-08 15:22 UTC, ChronosSF requested changes

2023-09-08 15:22 UTC, ChronosSF commented on doc/en/components/grids/_shared/display-density.md
>  ```typescript
this is left with `this` for react

2023-09-11 12:43 UTC, ChronosSF commented
Still a codesnippet with this under http://localhost:3000/components/grids/grid/display-density.html#usage - in the 'or' section.

2023-09-11 13:12 UTC, mddragnev commented
> Still a codesnippet with this under http://localhost:3000/components/grids/grid/display-density.html#usage - in the 'or' section.

@ChronosSF should be ok now

2023-09-11 13:39 UTC, ChronosSF approved these changes

2023-09-11 13:39 UTC, merged