RowActions initial
IgniteUI/igniteui-xplat-docs pull request #963
Opened 2023-09-04 11:20 UTC by tishko0

2023-09-11 14:32 UTC, ChronosSF requested changes

2023-09-11 14:32 UTC, ChronosSF commented on doc/en/components/grids/_shared/row-actions.md
> +```html
needs to be changed to ```tsx

2023-09-11 14:32 UTC, ChronosSF commented on doc/en/components/grids/_shared/row-actions.md
> +```html
needs to be changed to ```tsx

2023-09-26 11:57 UTC, ChronosSF requested changes
You should double check this document. The second header ```## Custom Implementation``` is only visible for Angular because of a condition. This means that the Blazor code snippet is lost and the WC and React codesnippets don't have any section and are just appended to Usage.

In addition the WC and React code snippets kind of miss the point. They simply show the editing actions props while the idea of the paragraph is to show custom buttons like in the Blazor and Angular snippets.

2023-09-28 11:12 UTC, IMinchev64 commented
> You should double check this document. The second header `## Custom Implementation` is only visible for Angular because of a condition. This means that the Blazor code snippet is lost and the WC and React codesnippets don't have any section and are just appended to Usage.
> 
> In addition the WC and React code snippets kind of miss the point. They simply show the editing actions props while the idea of the paragraph is to show custom buttons like in the Blazor and Angular snippets.

Currently, only Angular supports the custom implementation, which is why only Angular has such a section in the documentation topics for now. The reason behind this limitation is that the required CRUD service is not yet exported, which prevents creating a custom button with an associated click event for the other platforms.

2023-09-29 05:52 UTC, mddragnev submitted a review, later dismissed

2023-09-29 05:52 UTC, mddragnev commented on doc/en/components/grids/_shared/row-actions.md
> +<{ComponentName} id="grid" rowEditable="true" primaryKey="ID">
This should be ComponentSelector like the next react snippet below

2023-09-29 11:19 UTC, ChronosSF approved these changes

2023-09-29 11:20 UTC, merged